#!/bin/sh

# This script injects a "test-mode" file into a copy of the main disk
# image.  It begins by parsing the partition table of the disk image
# to identify either the 'aux' or 'esp' partition, which is then
# extracted. An empty 'test-mode' file is injected into the extracted
# partition, and the modified partition is written back to the output
# image. The output image can subsequently be used as a backing image
# for Copy-on-Write (QCOW) images utilized by Qeneth.

set -e

die()
{
    echo "ERROR: $*" >&2
    exit 1
}

workdir=$(mktemp -d)
trap 'rm -rf "$workdir"' EXIT INT TERM


baseimg="$1"
testimg="$2"

basegpt="$workdir"/basegpt.json
sfdisk -J "$baseimg" >"$basegpt"

lbsize=$(jq -r .partitiontable.sectorsize $basegpt)

jq -r '.partitiontable.partitions[]
		| select(.name == "aux" or .name == "esp")
		| "\(.name) \(.start) \(.size)"' $basegpt | {
    read part start size

    [ "$part" ] || die "Disk must contain either aux or esp partition"


    dd status=none \
       if="$baseimg" \
       bs=$lbsize skip=$start count=$size \
       of="$workdir"/markerpart \
	|| die "Unable to extract marker partition"

    touch "$workdir"/empty

    case "$part" in
	aux)
	    e2cp "$workdir"/empty "$workdir"/markerpart:/test-mode \
		 || die "Unable to inject test-mode in aux"
	    ;;
	esp)
	    mcopy -i "$workdir"/markerpart "$workdir"/empty ::/test-mode \
		|| die "Unable to inject test-mode in esp"
	    ;;
    esac

    cp -f "$baseimg" "$testimg" || die "Unable to create $testimg"
    dd status=none conv=notrunc \
       if="$workdir"/markerpart \
       bs=$lbsize seek=$start count=$size \
       of="$testimg" \
       || die "Unable to inject markerpartition in $testimg"
}
