# Enabled by confd when /ietf-snmp:snmp/engine/enabled is true.  Needs
# the /var/run/agentx directory, see /etc/tmpfiles.d/snmpd.conf, for
# subagents like lldpd to attach to.
service [2345] env:-/etc/default/snmpd /usr/sbin/snmpd -f -LOw \
	-p /run/snmpd.pid $SNMPD_ARGS \
	-- Net-SNMP daemon
