/* SPDX-License-Identifier: BSD-3-Clause */

#include <srx/lyx.h>
#include <srx/srx_val.h>

#include "core.h"
#include "dagger.h"
#include "interfaces.h"

/*
 * Modem interface lifecycle management
 *
 * The kernel (cdc_mbim, qmi_wwan driver) creates the wwan interface automatically
 * when a USB modem attaches.  confd does NOT need to run 'ip link add'.  Instead:
 *
 * - On CREATE: generate a dagger init script that waits for the wwan interface to
 *   appear in sysfs.  If hardware is absent (no modem detected), create a dummy
 *   placeholder so that downstream IP/address config works.  Signal modemd to
 *   (re)connect with the latest bearer config.
 *
 * - On DELETE: remove the /etc/net.d/<ifname>.conf route file so that netd/FRR
 *   withdraws the default route.  Then delete the interface — either the real
 *   wwan one or the dummy placeholder.
 *
 * Address management is handled by modemd (analogous to the udhcpc script for
 * DHCP).  modemd uses 'ip addr add ... proto wwan' so that protocol-tagged flush
 * on disconnect is precise and does not touch addresses added by other means.
 *
 * Routes are written by modemd to /etc/net.d/<ifname>.conf, picked up by netd
 * via inotify, and installed by staticd/zebra.  This keeps all routes visible to
 * FRR and enables proper metric-based failover behind wired/WiFi interfaces.
 */

static int modem_get_probe_timeout(sr_session_ctx_t *session, const char *modem)
{
	char *str;
	int timeout = 0;

	str = srx_get_str(session,
		"/ietf-hardware:hardware/component[name='%s']/infix-hardware:modem/probe-timeout",
		modem);
	if (str) {
		timeout = atoi(str);
		free(str);
	}
	return timeout;
}

int modem_add_iface(struct lyd_node *cif, struct dagger *net)
{
	const char *ifname = lydx_get_cattr(cif, "name");
	struct lyd_node *wwan = lydx_get_child(cif, "wwan");
	const char *modem_hw = wwan ? lydx_get_cattr(wwan, "modem") : NULL;
	int probe_timeout = 0;
	FILE *sh;

	if (modem_hw)
		probe_timeout = modem_get_probe_timeout(net->session, modem_hw);

	sh = dagger_fopen_net_init(net, ifname, NETDAG_INIT_PRE, "modem-iface.sh");
	if (!sh) {
		ERRNO("Failed to open dagger file for modem interface creation");
		return SR_ERR_INTERNAL;
	}

	/* Wait for wwan interface if probe-timeout is set (slow USB modems) */
	if (probe_timeout > 0) {
		fprintf(sh, "timeout=%d\n", probe_timeout);
		fprintf(sh, "while [ $timeout -gt 0 ]; do\n");
		fprintf(sh, "    ip link show %s >/dev/null 2>&1 && break\n", ifname);
		fprintf(sh, "    sleep 1\n");
		fprintf(sh, "    timeout=$((timeout - 1))\n");
		fprintf(sh, "done\n");
	}

	/* If interface doesn't exist, create a dummy placeholder so downstream IP config works.
	 * modemd will reconfigure the real interface once the modem attaches. */
	fprintf(sh, "if ! ip link show %s >/dev/null 2>&1; then\n", ifname);
	fprintf(sh, "    logger -t modem \"%s: interface not yet available, creating dummy placeholder\"\n", ifname);
	fprintf(sh, "    ip link add %s type dummy\n", ifname);
	fprintf(sh, "fi\n\n");

	/* Signal modemd to pick up any updated bearer config. */
	fprintf(sh, "initctl -bfq touch modemd 2>/dev/null || true\n");

	fclose(sh);
	return SR_ERR_OK;
}

int modem_del_iface(struct lyd_node *dif, struct dagger *net)
{
	const char *ifname = lydx_get_cattr(dif, "name");
	FILE *sh;

	sh = dagger_fopen_net_exit(net, ifname, NETDAG_EXIT_POST, "modem-iface.sh");
	if (!sh) {
		ERRNO("Failed to open dagger file for modem interface deletion");
		return SR_ERR_INTERNAL;
	}

	fprintf(sh, "# Generated by Infix confd - Modem Interface Cleanup\n\n");

	/* Remove route config so netd/FRR withdraws the default route */
	fprintf(sh, "rm -f /etc/net.d/%s.conf\n", ifname);

	/* Bring down and remove — works for both real wwan and dummy placeholder */
	fprintf(sh, "ip link set %s down 2>/dev/null || true\n", ifname);
	fprintf(sh, "ip link del %s 2>/dev/null || true\n", ifname);

	fclose(sh);
	return SR_ERR_OK;
}
