/* SPDX-License-Identifier: BSD-3-Clause */
/*
 * PPP links, so far only PPPoE client sessions
 *
 * The kernel removes a ppp interface when the file that created it is
 * closed, so the interface needs a process to own it: pppmon.  dagger
 * starts pppmon when the interface is created, before the rest of its
 * setup, and stops it when the interface is deleted.  The interface is
 * then configured like any other, except for what pppd owns: its link
 * state and MTU.
 *
 * pppd is a Finit service, pppd@IFNAME, that attaches to the interface
 * held by pppmon, using the unit pppmon writes to its options file.
 * confd writes the peers file for pppd, and an env file for the service
 * that pppd's ip-up script reads too.  ip-up hands the default route to
 * netd and the peer DNS servers to resolvconf.  Finit restarts pppd when
 * the env file changes, and confd touches the service when the peers
 * file does, since pppd only reads its options at start.
 *
 * TCP MSS clamping for a PPPoE session is an nftables table of its own,
 * matching the interface by name, so it does not depend on the firewall
 * being enabled.
 */

#include <ctype.h>

#include <srx/lyx.h>
#include <srx/srx_val.h>

#include "interfaces.h"
#include "base64.h"

#define PPP_PEERS    "/etc/ppp/peers/%s"
#define PPP_SETTINGS "/etc/default/pppd-%s"
#define PPP_NFT      "/etc/ppp/%s.nft"
#define PPPD_PID     "/run/pppd/ppp-%s.pid"	/* from pppd's linkname */
#define PPPMON_OPTS  "/run/pppmon-%s.opts"
#define PPPMON_PID   "/run/pppmon-%s.pid"

/*
 * The password is written in double quotes into the peers file, so it
 * cannot hold a '"', '\', or control characters.  Returns the decoded
 * password, or NULL with an error message when it is missing or bad.
 */
static char *ppp_secret(sr_session_ctx_t *session, struct lyd_node *cif)
{
	const char *ifname = lydx_get_cattr(cif, "name");
	const char *name, *b64;
	struct lyd_node *key;
	unsigned char *pw;
	size_t len;

	name = lydx_get_cattr(lydx_get_child(cif, "ppp"), "secret");
	key = lydx_get_xpathf(cif, "../../keystore/symmetric-keys/symmetric-key[name='%s']", name);
	b64 = lydx_get_cattr(key, "cleartext-symmetric-key");
	if (!b64 || !*b64) {
		if (session)
			sr_session_set_error_message(session, "%s: PPP secret \"%s\" has no cleartext value",
						     ifname, name);
		return NULL;
	}

	pw = base64_decode((const unsigned char *)b64, strlen(b64), &len);
	if (!pw)
		return NULL;

	for (size_t i = 0; i < len; i++) {
		if (iscntrl(pw[i]) || pw[i] == '"' || pw[i] == '\\') {
			if (session)
				sr_session_set_error_message(session, "%s: PPP password may not contain "
							     "control characters, '\"', or '\\'", ifname);
			free(pw);
			return NULL;
		}
	}

	return (char *)pw;
}

int ppp_validate_secret(sr_session_ctx_t *session, struct lyd_node *cif)
{
	char *pw;

	pw = ppp_secret(session, cif);
	if (!pw)
		return SR_ERR_VALIDATION_FAILED;

	free(pw);
	return SR_ERR_OK;
}

static int ppp_gen_peers(struct lyd_node *cif, const char *pw)
{
	const char *ifname = lydx_get_cattr(cif, "name");
	struct lyd_node *ppp, *pppoe, *ipv6;
	const char *val;
	mode_t oldmask;
	FILE *fp;

	ppp = lydx_get_child(cif, "ppp");
	pppoe = lydx_get_child(cif, "pppoe");
	ipv6 = lydx_get_child(cif, "ipv6");

	oldmask = umask(0077);
	fp = fopenf("w", PPP_PEERS "+", ifname);
	umask(oldmask);
	if (!fp)
		return -EIO;

	fprintf(fp, "# Generated by Infix confd\n");
	fprintf(fp, "plugin pppoe.so\n");
	fprintf(fp, "nic-%s\n", lydx_get_cattr(pppoe, "lower-layer-if"));
	if ((val = lydx_get_cattr(pppoe, "service-name")))
		fprintf(fp, "pppoe-service \"%s\"\n", val);
	if ((val = lydx_get_cattr(pppoe, "ac-name")))
		fprintf(fp, "pppoe-ac \"%s\"\n", val);
	fprintf(fp, "user \"%s\"\n", lydx_get_cattr(ppp, "username"));
	fprintf(fp, "password \"%s\"\n", pw);
	fprintf(fp, "hide-password\n");
	fprintf(fp, "noauth\n");
	fprintf(fp, "noipdefault\n");
	/* Routes go through netd, see /etc/ppp/ip-up */
	fprintf(fp, "nodefaultroute\n");
	if (lydx_is_enabled(ppp, "peer-dns"))
		fprintf(fp, "usepeerdns\n");
	if (ipv6 && lydx_is_enabled(ipv6, "enabled"))
		fprintf(fp, "+ipv6\n");
	else
		fprintf(fp, "noipv6\n");
	/* Keep trying, the server or the uplink may come back */
	fprintf(fp, "persist\n");
	fprintf(fp, "maxfail 0\n");
	fprintf(fp, "holdoff 5\n");
	fprintf(fp, "lcp-echo-interval 10\n");
	fprintf(fp, "lcp-echo-failure 3\n");
	fclose(fp);

	return 0;
}

static int ppp_gen_settings(struct lyd_node *cif)
{
	const char *ifname = lydx_get_cattr(cif, "name");
	struct lyd_node *ppp = lydx_get_child(cif, "ppp");
	FILE *fp;

	fp = fopenf("w", PPP_SETTINGS "+", ifname);
	if (!fp)
		return -EIO;

	fprintf(fp, "# Generated by Infix confd, read by pppd@%s and /etc/ppp/ip-up\n", ifname);
	fprintf(fp, "DEFAULT_ROUTE=%d\n", lydx_is_enabled(ppp, "default-route"));
	fprintf(fp, "ROUTE_PREFERENCE=%s\n", lydx_get_cattr(ppp, "route-preference"));
	fclose(fp);

	return 0;
}

/* Replace file with file+ if they differ: 1 if replaced, 0 if not, -1 on error */
static int ppp_update(const char *fmt, const char *ifname)
{
	char path[256], next[260];

	snprintf(path, sizeof(path), fmt, ifname);
	snprintf(next, sizeof(next), "%s+", path);

	if (!systemf("cmp -s %s %s", path, next)) {
		(void)remove(next);
		return 0;
	}

	if (rename(next, path)) {
		ERRNO("%s: failed replacing %s", ifname, path);
		return -1;
	}

	return 1;
}

/*
 * Clamp the MSS of TCP connections forwarded through the session, both
 * directions, to the route MTU.  The table is replaced as a whole, nft
 * runs the file as one transaction.
 */
static int ppp_gen_mss(struct lyd_node *cif)
{
	const char *ifname = lydx_get_cattr(cif, "name");
	FILE *fp;

	fp = fopenf("w", PPP_NFT, ifname);
	if (!fp)
		return -EIO;

	fprintf(fp, "# Generated by Infix confd\n");
	fprintf(fp, "add table inet pppoe-%s\n", ifname);
	fprintf(fp, "delete table inet pppoe-%s\n", ifname);
	fprintf(fp, "table inet pppoe-%s {\n", ifname);
	fprintf(fp, "\tchain mss-clamping {\n");
	fprintf(fp, "\t\ttype filter hook forward priority mangle; policy accept;\n");
	fprintf(fp, "\t\toifname \"%s\" tcp flags syn / syn,rst tcp option maxseg size set rt mtu\n", ifname);
	fprintf(fp, "\t\tiifname \"%s\" tcp flags syn / syn,rst tcp option maxseg size set rt mtu\n", ifname);
	fprintf(fp, "\t}\n");
	fprintf(fp, "}\n");
	fclose(fp);

	return 0;
}

int ppp_gen(sr_session_ctx_t *session, struct lyd_node *dif, struct lyd_node *cif,
	    struct dagger *net)
{
	const char *ifname = lydx_get_cattr(cif, "name");
	int restart;
	FILE *sh;
	char *pw;
	int err;

	pw = ppp_secret(session, cif);
	if (!pw)
		return -EINVAL;

	err = ppp_gen_peers(cif, pw);
	free(pw);
	err = err ? : ppp_gen_settings(cif);
	err = err ? : ppp_gen_mss(cif);
	if (err)
		return err;

	/* Finit restarts pppd on its own when the env file changes */
	if (ppp_update(PPP_SETTINGS, ifname) < 0)
		return -EIO;
	restart = ppp_update(PPP_PEERS, ifname);
	if (restart < 0)
		return -EIO;

	if (lydx_is_enabled(cif, "enabled")) {
		finit_enablef("pppd@%s", ifname);
		if (restart)
			finit_reloadf("pppd@%s", ifname);
	} else {
		finit_disablef("pppd@%s", ifname);
	}

	/* Runs before the rest of the interface setup, which needs it */
	sh = dagger_fopen_net_init(net, ifname, NETDAG_INIT_PRE, "pppmon.sh");
	if (!sh)
		return -EIO;

	/* pppmon goes to the background once the interface exists */
	if (lydx_get_op(dif) == LYDX_OP_CREATE)
		fprintf(sh, "/usr/libexec/confd/pppmon -o " PPPMON_OPTS " -p " PPPMON_PID
			" %s || exit 1\n", ifname, ifname, ifname);

	if (lydx_is_enabled(lydx_get_child(cif, "pppoe"), "mss-clamping"))
		fprintf(sh, "nft -f " PPP_NFT "\n", ifname);
	else
		fprintf(sh, "nft delete table inet pppoe-%s 2>/dev/null\n", ifname);
	fclose(sh);

	return 0;
}

/* Wait for the process in pidfile to exit */
static void ppp_wait(FILE *sh, const char *pidfn)
{
	fprintf(sh, "if pid=$(cat %s 2>/dev/null); then\n"
		"\twhile kill -0 $pid 2>/dev/null; do sleep 0.1; done\n"
		"fi\n", pidfn);
}

int ppp_del(struct lyd_node *dif, struct dagger *net)
{
	const char *ifname = lydx_get_cattr(dif, "name");
	char pppd[64], pppmon[64];
	FILE *sh;

	snprintf(pppd, sizeof(pppd), PPPD_PID, ifname);
	snprintf(pppmon, sizeof(pppmon), PPPMON_PID, ifname);

	sh = dagger_fopen_net_exit(net, ifname, NETDAG_EXIT_DAEMON, "pppmon.sh");
	if (!sh)
		return -EIO;

	finit_disablef("pppd@%s", ifname);

	/* pppd hangs up first, then the interface goes with pppmon */
	fprintf(sh, "initctl -bnq stop pppd:%s\n", ifname);
	ppp_wait(sh, pppd);
	fprintf(sh, "kill $(cat %s) 2>/dev/null\n", pppmon);
	ppp_wait(sh, pppmon);
	fprintf(sh, "nft delete table inet pppoe-%s 2>/dev/null\n", ifname);
	fprintf(sh, "rm -f " PPP_PEERS " " PPP_SETTINGS " " PPP_NFT "\n",
		ifname, ifname, ifname);
	fclose(sh);

	return 0;
}

int ppp_add_deps(struct lyd_node *cif)
{
	const char *lower;
	int err;

	lower = lydx_get_cattr(lydx_get_child(cif, "pppoe"), "lower-layer-if");
	err = dagger_add_dep(&confd.netdag, lydx_get_cattr(cif, "name"), lower);
	if (err)
		return ERR_IFACE(cif, err, "Unable to depend on \"%s\"", lower);

	return 0;
}
