/* SPDX-License-Identifier: BSD-3-Clause */
#include <srx/lyx.h>

#include "ietf-interfaces.h"

#define WPA_SUPPLICANT_CONF "/etc/finit.d/available/wpa-supplicant-%s.conf"
int wifi_gen(struct lyd_node *dif, struct lyd_node *cif, struct dagger *net)
{
	const char *ssid, *secret, *ifname, *country, *encryption;
	FILE *wpa_supplicant = NULL, *finit = NULL;
	struct lyd_node *wifi;
	char *encryption_str;
	FILE *wpa = NULL;

	ifname = lydx_get_cattr(cif, "name");
	wifi   = lydx_get_child(cif, "wifi");
	ssid   = lydx_get_cattr(wifi, "ssid");
	secret = lydx_get_cattr(wifi, "secret");
	country = lydx_get_cattr(wifi, "country-code");
	encryption = lydx_get_cattr(wifi, "encryption");

	finit = fopenf("w", WPA_SUPPLICANT_CONF, ifname);
	if (!finit)
		return SR_ERR_INTERNAL;

	fprintf(finit, "# Generated by Infix confd\n");
	fprintf(finit, "service <!> name:wpa_supplicant :%s <> \\\n"
		"	[2345] wpa_supplicant -s -i %s -c /etc/wpa-supplicant-%s.conf \\\n"
		"		-- WPA supplicant @%s\n", ifname, ifname, ifname, ifname);
	fclose(finit);
	wpa = dagger_fopen_net_init(net, ifname, NETDAG_INIT_POST, "wpa-supplicant.sh");
	if (!wpa)
		return SR_ERR_INTERNAL;

	fprintf(wpa, "# Generated by Infix confd\n");
	fprintf(wpa, "set -e\n");
	fprintf(wpa, "initctl -bfqn enable wpa-supplicant-%s", ifname);
	fclose(wpa);

	wpa_supplicant = fopenf("w", "/etc/wpa-supplicant-%s.conf", ifname);
	if (!wpa_supplicant)
		return SR_ERR_INTERNAL;

	if (!strcmp(encryption, "disabled"))
		asprintf(&encryption_str, "key_mgmt=NONE");
	else
		asprintf(&encryption_str, "psk=\"%s\"", secret);

	fprintf(wpa_supplicant,
		"country=%s\n"
		"ctrl_interface=/run/wpa_supplicant\n"
		"network={\n"
		"ssid=\"%s\"\n"
		"%s\n"
		"}", country, ssid, encryption_str);
	free(encryption_str);
	fclose(wpa_supplicant);

	return SR_ERR_OK;
}

int wifi_gen_del(struct lyd_node *dif,  struct dagger *net)
{
	const char *ifname = lydx_get_cattr(dif, "name");
	FILE *iw = dagger_fopen_net_exit(net, ifname, NETDAG_EXIT_PRE, "iw.sh");

	fprintf(iw, "# Generated by Infix confd\n");
	fprintf(iw, "iw dev %s disconnect\n", ifname);
	fprintf(iw, "initctl -bfqn disable wpa-supplicant-%s", ifname);
	fclose(iw);
	erasef(WPA_SUPPLICANT_CONF, ifname);

	return SR_ERR_OK;
}

int wifi_scan(sr_session_ctx_t *session, uint32_t sub_id, const char *xpath,
              const sr_val_t *input, const size_t input_cnt,
              sr_event_t event, unsigned request_id,
              sr_val_t **output, size_t *output_cnt,
              void *priv)
{
	char xpath_copy[strlen(xpath) + 1];
	sr_xpath_ctx_t ctx = {0};
	sr_val_t *values = NULL;
	size_t entry_count = 0;
	int ret = SR_ERR_OK;
	const char *ssid;
	json_t *network;
	int count = 0;
	json_t *root;
	FILE *fp;

	strcpy(xpath_copy, xpath);

	const char *ifname = sr_xpath_key_value(xpath_copy, "interface", "name", &ctx);
	if (!ifname) {
		ERROR("Could not extract interface name from xpath: %s", xpath);
		return SR_ERR_INVAL_ARG;
	}

	/* creates the file /tmp/networks-<ifname>.json */
	if (systemf("/usr/libexec/confd/wifi-scan -i %s", ifname)) {
		ERROR("wifi-scan failed on %s", ifname);
		return SR_ERR_INTERNAL;
	}

	fp = fopenf("r", "/tmp/networks-%s.json", ifname);
	if (!fp) {
		ERROR("Could not open /tmp/networks-%s.json", ifname);
		return SR_ERR_INTERNAL;
	}

	root = json_loadf(fp, 0, NULL);
	fclose(fp);
	if (!root) {
		ERROR("Could not parse JSON in /tmp/networks-%s.json", ifname);
		return SR_ERR_INTERNAL;
	}

	json_object_foreach(root, ssid, network) {
		if (json_is_object(network))
			entry_count++;
	}

	if (entry_count == 0) {
		json_decref(root);
		*output = NULL;
		*output_cnt = 0;
		return SR_ERR_OK;
	}

	ret = sr_new_values(entry_count * 4, &values);
	if (ret != SR_ERR_OK) {
		json_decref(root);
		return ret;
	}

	json_object_foreach(root, ssid, network) {
		char security_xpath[1024];
		char channel_xpath[1024];
		char base_xpath[1024];
		char rssi_xpath[1024];
		json_t *frequency;
		json_t *security;
		json_t *channel;
		json_t *signal;
		json_t *bssid;

		if (!json_is_object(network)) {
			ERROR("Invalid object for SSID: %s\n", ssid);
			continue;
		}

		bssid = json_object_get(network, "bssid");
		signal = json_object_get(network, "signal");
		frequency = json_object_get(network, "frequency");
		channel = json_object_get(network, "channel");
		security = json_object_get(network, "security");

		if (!json_is_string(bssid) ||
		    !json_is_number(signal) ||
		    !json_is_number(frequency) ||
		    !json_is_integer(channel) ||
		    !json_is_string(security)) {
			ERROR("Skipping malformed entry for %s\n", ssid);
			continue;
		}

		snprintf(base_xpath, sizeof(base_xpath), "%s/ssids[ssid='%s']", xpath, ssid);

		ret = sr_val_set_xpath(&values[count], base_xpath);
		if (ret != SR_ERR_OK)
			goto cleanup;
		ret = sr_val_set_str_data(&values[count], SR_STRING_T, ssid);
		if (ret != SR_ERR_OK)
			goto cleanup;
		count++;

		snprintf(rssi_xpath, sizeof(rssi_xpath), "%s/rssi", base_xpath);
		ret = sr_val_set_xpath(&values[count], rssi_xpath);
		if (ret != SR_ERR_OK)
			goto cleanup;
		values[count].type = SR_INT16_T;
		values[count].data.int16_val = (int16_t)json_number_value(signal);
		count++;

		snprintf(channel_xpath, sizeof(channel_xpath), "%s/channel", base_xpath);
		ret = sr_val_set_xpath(&values[count], channel_xpath);
		if (ret != SR_ERR_OK)
			goto cleanup;
		values[count].type = SR_INT16_T;
		values[count].data.int16_val = (int16_t)json_integer_value(channel);
		count++;

		snprintf(security_xpath, sizeof(security_xpath), "%s/security", base_xpath);
		ret = sr_val_set_xpath(&values[count], security_xpath);
		if (ret != SR_ERR_OK)
			goto cleanup;
		ret = sr_val_set_str_data(&values[count], SR_STRING_T, json_string_value(security));
		if (ret != SR_ERR_OK)
			goto cleanup;
		count++;
	}

	json_decref(root);
	*output = values;
	*output_cnt = count;
	return SR_ERR_OK;

cleanup:
	if (values) {
		sr_free_values(values, count);
	}
	json_decref(root);
	return ret;
}
