name: 'Podman Cleanup'
description: 'Clean up stale podman state from previous runs'
runs:
  using: 'composite'
  steps:
    - name: Cleanup podman state
      shell: bash
      run: |
        set -x
        podman ps -a              || true
        podman stop -a            || true
        podman rm -a -f           || true
        podman volume prune -f    || true
        podman system prune -a -f || true
        podman system migrate     || true
