# Microchip EV23X71A (Laguna) kernel configuration fixups
define MICROCHIP_EV23X71A_LINUX_CONFIG_FIXUPS
	# LAN969x SoC
	$(call KCONFIG_ENABLE_OPT,CONFIG_ARCH_LAN969X)
	$(call KCONFIG_ENABLE_OPT,CONFIG_COMMON_CLK_LAN966X)
	$(call KCONFIG_ENABLE_OPT,CONFIG_PINCTRL_OCELOT)

	# Serial console (FLEXCOM), ttyAT naming to match the bootloader
	$(call KCONFIG_ENABLE_OPT,CONFIG_MFD_ATMEL_FLEXCOM)
	$(call KCONFIG_ENABLE_OPT,CONFIG_SERIAL_ATMEL)
	$(call KCONFIG_ENABLE_OPT,CONFIG_SERIAL_ATMEL_CONSOLE)
	$(call KCONFIG_ENABLE_OPT,CONFIG_SERIAL_ATMEL_TTYAT)

	# Switch core, SerDes, and MDIO
	$(call KCONFIG_ENABLE_OPT,CONFIG_SPARX5_SWITCH)
	$(call KCONFIG_ENABLE_OPT,CONFIG_LAN969X_SWITCH)
	$(call KCONFIG_ENABLE_OPT,CONFIG_PHY_SPARX5_SERDES)
	$(call KCONFIG_ENABLE_OPT,CONFIG_MDIO_MSCC_MIIM)
	$(call KCONFIG_SET_OPT,CONFIG_MICROSEMI_PHY,m)

	# eMMC
	$(call KCONFIG_ENABLE_OPT,CONFIG_MMC_SDHCI_PLTFM)
	$(call KCONFIG_ENABLE_OPT,CONFIG_MMC_SDHCI_OF_AT91)

	# I2C, SPI, and DMA
	$(call KCONFIG_ENABLE_OPT,CONFIG_I2C_AT91)
	$(call KCONFIG_ENABLE_OPT,CONFIG_SPI_ATMEL)
	$(call KCONFIG_ENABLE_OPT,CONFIG_AT_XDMAC)

	# Watchdog and entropy
	$(call KCONFIG_ENABLE_OPT,CONFIG_DW_WATCHDOG)
	$(call KCONFIG_SET_OPT,CONFIG_HW_RANDOM_ATMEL,m)
endef

$(eval $(ix-board))
$(eval $(generic-package))
