#!/usr/bin/env python3
"""
   Main server loop.
"""
import sys

from flask       import Flask#, render_template_string
from avahi_alias import AvahiAlias
from mdns_hosts  import MdnsHosts

app = Flask(__name__)

@app.route('/browse')
def browse():
    """The /browse network.local application"""
    mdns_hosts = MdnsHosts()
    content = mdns_hosts.html().encode('utf-8')
    #return render_template_string(content)
    return content

if __name__ == '__main__':
    avahi_aliases = AvahiAlias()
    for each in sys.argv[1:]:
        avahi_aliases.publish_cname(str(each).encode("utf-8", "strict"))

    try:
        app.run(debug=True)
    except KeyboardInterrupt:
        print("Exiting")
