#!/bin/sh

reserved()
{
    for svc in avahi dnsmasq getty klish lldpd nginx rauc ssdpd sshd sysklogd sysrepo; do
	[ "$1" = "${svc}.conf" ] && return 0
    done

    return 1
}

for file in /etc/finit.d/enabled/*.conf; do
    reserved "$(basename "$file")" && continue
    rm "$file"
done
