# Single daemon handles gen-config, datastore init, config load, and plugins
service log:console env:/etc/default/confd        \
	[S12345] <usr/ixinit> confd -f -v warning \
		-F /etc/factory-config.cfg        \
		-S /cfg/startup-config.cfg        \
		-E /etc/failure-config.cfg        \
		-t $CONFD_TIMEOUT                 \
		$CONFD_ARGS                       \
	-- Configuration daemon
