# Run user scripts from /etc/rc.d once at boot, after the startup
# configuration has been applied, see /system/advanced/rc.d
task [2345] name:rcd log <usr/bootstrap> \
	/usr/libexec/finit/runparts -bp /etc/rc.d -- Running rc.d scripts
