#!/bin/sh

# This is an unmanaged node, leave /etc as-is
[ -f /mnt/cfg/infix/.use_etc ] && exit 0
initctl cond get boot/etc  && exit 0

# This is a managed node, ignore all default configuration...
rm -f /etc/rc.local
rm -rf /etc/finit.d/enabled/*.conf
rm -rf /etc/network/interfaces*

#...except for some core services
for svc in getty sysklogd; do
    ln -s ../available/$svc.conf /etc/finit.d/enabled/$svc.conf
done
