#!/bin/sh

# Called from /etc/fstab to ensure we have something writable mounted
# at /rw, which is used by Infix to store device modifications made
# to /etc, /home, /root, and /var/lib.
#
# If a disk partiion labeled "infix-rw" is available, that is used to
# persist changes to the aforementioned directories. Otherwise fall
# back to a tmpfs based RAM disk. This effectively brings up the
# system with the default configuration, but obviously any subsequent
# configuration is ephemeral.

set -e

nm=$(basename $0)
err=0
opt="-k"

mount_rw()
{
    # If something is already setup, leave it be.
    mountpoint -q /rw && return 0

    # TODO: Also look for UBI partitions
    mount $tab LABEL=infix-rw && return 0

    return 1
}

if ! mount_rw; then
    err=1

    logger $opt -p user.crit -t "$nm" \
	   "No persistent storage found for /rw, falling back to tmpfs."

    mount tmpfs-rw
fi

# fall back to console logging if sysklogd is too old
if ! logger -? |grep -q "Log to kernel"; then
    opt="-c"
fi

# Allow users in wheel group to write to /rw
chgrp wheel /rw && chmod g+w   /rw

# Check for factory reset
if [ -f /rw/infix/.reset ]; then
	logger $opt -p user.crit -t "$nm" "Resetting to factory defaults."
	rm -rf /rw/infix/* /rw/infix/.reset
	sync
fi

exit $err
