#!/bin/sh
# Called from /etc/fstab to ensure we have something writable mounted
# at /cfg, /home, /root, and /var.
#
# In the normal case, the "rw" LV from the "internal" LVM VG is used
# to back all persistant storage. In the event that "internal" is
# present, but the "rw" LV is missing, one will be provisioned, along
# with the required BTRFS subvolumes.
#
# In all other scenarios where the subvolumes are not available, the
# system will fall back to temporary storage for all mount points.
#
# For /etc, a writable, tmpfs backed, layer is always overlayed on top
# of the read-only contents from the OS image.

set -e

nm=$(basename "$0")
need_restore=
code=0

logcrit()
{
    logger -k -t "$nm" -p user.crit "$@"
}

lognote()
{
    logger -k -t "$nm" -p user.notice "$@"
}

status()
{
    GREEN="$(printf '\033[1;32m')"
    RED="$(printf '\033[1;31m')"
    YELLOW="$(printf '\033[1;33m')"
    BOLD="$(printf '\033[1m')"
    RESET="$(printf '\033[0m')"

    case $1 in
        0) color=$GREEN; text=' OK ' ;;
        1) color=$RED;   text='FAIL' ;;
        2) color=$YELLOW;text='WARN' ;;
        *) color=$YELLOW;text=' ⋯  ' ;;
    esac

    printf '%s[%s%s%s%s]%s ' "$BOLD" "$color" "$text" "$RESET" "$BOLD" "$RESET"
}

print_start()
{
    printf '\r\033[K%s%s' "$(status 3)" "$*" > /dev/console
    need_restore=YES
}

print_end()
{
    rc=$1; shift
    if [ $# -gt 0 ]; then
        printf '\r\033[K%s%s\n' "$(status "$rc")" "$*" > /dev/console
    else
        printf '\r%s\n' "$(status "$rc")" > /dev/console
    fi
}

# Restore Finit's original progress message so its [ OK ] appears correctly
print_restore()
{
    [ "$need_restore" ] || return 0
    print_start "Mounting filesystems from /etc/fstab"
}

internal_rw_factory_reset()
{
    factory --check-clear || return 0
    [ -b /dev/internal/rw ] || return 0

    print_start "Resetting to factory defaults"
    lognote "Resetting to factory defaults"

    lvm lvremove -y internal/rw || {
	logcrit "Unable to remove rw volume"
	print_end 1
	return 0
    }

    lognote "Factory reset complete"
    print_end 0
}

subvols="cfg var root home"

internal_rw_provision()
{
    # The only condition under which we do BTRFS provisioning is when
    # the LV is absent. In all other failure scenarios: fall back to
    # tmpfs and let the user sort it out. This way we do not risk any
    # loss of data.
    [ -b /dev/internal/rw ] && return 0

    print_start "Provisioning persistent storage on internal volume"

    lvm lvcreate -y --name rw --extents 50%FREE internal || {
	logcrit "No rw LV available, nor could it be created"
	print_end 1
	return 1
    }

    mkfs.btrfs -L rw /dev/internal/rw || {
	logcrit "Could not create BTRFS on rw LV"
	print_end 1
	return 1
    }

    mount -t btrfs /dev/internal/rw /mnt/rw || {
	logcrit "Failed to mount rw"
	print_end 1
	return 1
    }

    for subvol in $subvols; do
	btrfs subvolume create /mnt/rw/@"$subvol" || {
	    logcrit "Failed to create @$subvol on rw"
	    print_end 1
	    return 1
	}
    done

    umount /mnt/rw || {
	logcrit "Failed to unmount rw"
	print_end 1
	return 1
    }

    print_end 0
}

internal_secondary_provision()
{
    local _free _size

    # On the first system boot, if a primary image is available, but a
    # secondary one is not, provision a duplicate of primary as the
    # secondary image. This let's the distribution disk image be
    # small, yet automatically deploys a redundant setup.
    [ -f /dev/firstboot ]          || return 0
    [ -b /dev/internal/primary ]   || return 0
    [ -b /dev/internal/secondary ] && return 0

    print_start "Provisioning redundant image"

    _free=$(lvm vgs --reportformat=json --units b internal \
		| jq -r .report[0].vg[0].vg_free \
		| tr -d B)
    _size=$(lvs --reportformat=json --units b internal/primary \
		| jq -r .report[0].lv[0].lv_size \
		| tr -d B)

    [ "$_free" -ge "$_size" ] || {
	logcrit "Skipping redundant $((_size >> 20))MB image, $((_free >> 20))MB available"
	print_end 1
	return 0
    }

    lvm lvcreate --name secondary --size "${_size}B" internal || {
	logcrit "Unable to create secondary LV"
	print_end 1
	return 1
    }

    dd if=/dev/internal/primary of=/dev/internal/secondary bs=1M status=none || {
	logcrit "Redundant image replication failed"
	print_end 1
	return 1
    }

    kpartx -a -p-part /dev/internal/secondary || {
	logcrit "Failed to setup partitions from replicated secondary image"
    }

    print_end 0
}

internal_activate()
{
    lvm vgs internal || {
	logcrit "No internal volume available"
	return 1
    }

    lvm vgchange -ay internal || {
	logcrit "Unable to bring internal volume online"
	return 1
    }

    internal_rw_factory_reset || return 1
    internal_rw_provision || return 1
    internal_secondary_provision || return 1
}

internal_rw_mount()
{
    [ -b /dev/internal/rw ] || return 1

    for subvol in $subvols; do
	mount -t btrfs /dev/internal/rw /"$subvol" -o subvol=@"$subvol" || {
	    logcrit "Failed to mount /$subvol"
	    return 1
	}
    done
}

tmpfs_rw_mount()
{
    for subvol in $subvols; do
	mkdir -p -m 0755 /mnt/tmp/"$subvol"
	mount /mnt/tmp/"$subvol" /"$subvol" -o bind || {
	    logcrit "Failed to mount temporary /$subvol"
	    return 1
	}
    done
}

tmpfs_etc_mount()
{
    mkdir -p -m 0755 /mnt/tmp/etc/
    tar c -C /etc . | tar x -C /mnt/tmp/etc
    mount /mnt/tmp/etc /etc -o bind
}

exec >/mnt/tmp/mnt.log 2>&1

tmpfs_etc_mount || {
    code=1
    logcrit "Failed to make /etc writable"
}

internal_activate || {
    print_end 1 "Activating internal volume"
}

internal_rw_mount || {
    code=1
    print_end 1 "Mounting persistent storage from internal volume"
    logcrit "Internal volume not found, falling back to tmpfs"

    print_start "Falling back to ephemeral tmpfs storage!"
    tmpfs_rw_mount
    print_end $?
}

print_restore
exit $code
