# PPP interface %i, held by pppmon, options in /etc/ppp/peers/%i
service <!net/%i/exist> name:pppd :%i env:/etc/default/pppd-%i \
	[2345] pppd call %i file /run/pppmon-%i.opts ifname %i linkname %i nodetach \
	-- PPP client @%i
