#!/bin/sh
# Command line arguments:
#   $1 event that happened:
#          BIND:     Successfully claimed address
#          CONFLICT: An IP address conflict happened
#          UNBIND:   The IP address is no longer needed
#          STOP:     The daemon is terminating
#   $2 interface name
#   $3 IP adddress

PATH="$PATH:/usr/bin:/usr/sbin:/bin:/sbin"

log()
{
    logger -I $$ -t zeroconf -p user.notice "$*"
}

# Use a different metric for each interface, so that we can set
# identical routes to multiple interfaces.
METRIC=$((1000 + `cat "/sys/class/net/$2/ifindex" 2>/dev/null || echo 0`))

case "$1" in
    BIND)
        ip addr flush dev "$2" label "$2:avahi"
        ip addr add "$3"/16 brd 169.254.255.255 label "$2:avahi" scope link dev "$2" proto random
        ip route add default dev "$2" metric "$METRIC" scope link proto zeroconf
	log "set ipv4ll $3 on iface $2"
        ;;

    CONFLICT|UNBIND|STOP)
        ip route del default dev "$2" metric "$METRIC" scope link
        ip addr flush dev "$2" label "$2:avahi"
	log "clr ipv4ll on iface $2"
        ;;

    *)
        log "Unknown event $1 on iface $2"
        exit 1
        ;;
esac

exit 0
