#!/bin/sh
# Command line arguments:
#   $1 event that happened:
#          BIND:     Successfully claimed address
#          CONFLICT: An IP address conflict happened
#          UNBIND:   The IP address is no longer needed
#          STOP:     The daemon is terminating
#   $2 interface name
#   $3 IP adddress
#
# For details on the distance adjustment below, please see the following
# section in the Frr documentation on distance + prefence => to metric.
# https://docs.frrouting.org/en/stable-8.0/zebra.html#administrative-distance

PATH="$PATH:/usr/bin:/usr/sbin:/bin:/sbin"

log()
{
    logger -I $$ -t zeroconf -p user.notice "$*"
}

# Use a different metric for each interface as tie breaker, to ensure we
# can set identical routes to multiple interfaces.
IFINDEX=$(cat "/sys/class/net/$2/ifindex" 2>/dev/null || echo 0)

# Distance adjustment to ensure that static routes set by Zebra and any
# routes learned from DHCP take precedence over these interface routes.
# A distance of 255 ensures these routes are never redistributed.
METRIC=$(((255 << 24) + 1000 + IFINDEX))

case "$1" in
    BIND)
        ip addr flush dev "$2" label "$2:avahi"
        ip addr add "$3"/16 brd 169.254.255.255 label "$2:avahi" scope link dev "$2" proto random
        ip route add default dev "$2" metric "$METRIC" scope link proto zeroconf
	log "set ipv4ll $3 on iface $2"
        ;;

    CONFLICT|UNBIND|STOP)
        ip route del default dev "$2" metric "$METRIC" scope link
        ip addr flush dev "$2" label "$2:avahi"
	log "clr ipv4ll on iface $2"
        ;;

    *)
        log "Unknown event $1 on iface $2"
        exit 1
        ;;
esac

exit 0
