define BANANAPI_BPI_R4_LINUX_CONFIG_FIXUPS
	$(call KCONFIG_ENABLE_OPT,CONFIG_ARCH_MEDIATEK)
	$(call KCONFIG_ENABLE_OPT,CONFIG_MACH_MT7988)
	$(call KCONFIG_ENABLE_OPT,CONFIG_PINCTRL_MT7988)
	$(call KCONFIG_ENABLE_OPT,CONFIG_SERIAL_8250_MT6577)
	$(call KCONFIG_SET_OPT,CONFIG_I2C_GPIO,y)
	$(call KCONFIG_SET_OPT,CONFIG_MTK_THERMAL,m)
	$(call KCONFIG_SET_OPT,CONFIG_MTK_LVTS_THERMAL,m)
	$(call KCONFIG_ENABLE_OPT,CONFIG_MTK_UART)
	$(call KCONFIG_ENABLE_OPT,CONFIG_MEDIATEK_WATCHDOG)
	$(call KCONFIG_ENABLE_OPT,CONFIG_MEDIATEK_GE_PHY)
	$(call KCONFIG_ENABLE_OPT,CONFIG_MEDIATEK_GE_SOC_PHY)
	$(call KCONFIG_ENABLE_OPT,CONFIG_NET_VENDOR_MEDIATEK)
	$(call KCONFIG_ENABLE_OPT,CONFIG_NET_MEDIATEK_SOC)
	$(call KCONFIG_SET_OPT,CONFIG_NET_DSA_MT7530,m)
	$(call KCONFIG_SET_OPT,CONFIG_MT7996E,m)
	$(call KCONFIG_SET_OPT,CONFIG_PCIE_MEDIATEK_GEN3,m)
	$(call KCONFIG_ENABLE_OPT,CONFIG_MTK_SCPSYS)
	$(call KCONFIG_ENABLE_OPT,CONFIG_MMC_MTK)
	$(call KCONFIG_SET_OPT,CONFIG_I2C_MT65XX,m)
	$(call KCONFIG_SET_OPT,CONFIG_USB_XHCI_MTK,m)
	$(call KCONFIG_SET_OPT,CONFIG_PHY_MTK_TPHY,m)
	$(call KCONFIG_SET_OPT,CONFIG_PHY_MTK_XSPHY,m)
	$(call KCONFIG_SET_OPT,CONFIG_PHY_MTK_XFI_TPHY,m)
	$(call KCONFIG_SET_OPT,CONFIG_PCS_STANDALONE,y)
	$(call KCONFIG_SET_OPT,CONFIG_PCS_MTK_USXGMII,y)
	$(call KCONFIG_SET_OPT,CONFIG_PWM_MEDIATEK,m)
	$(call KCONFIG_SET_OPT,CONFIG_SENSORS_PWM_FAN,m)
	$(call KCONFIG_SET_OPT,CONFIG_NVMEM_MTK_EFUSE,m)
	$(call KCONFIG_SET_OPT,CONFIG_MEDIATEK_2P5GE_PHY,m)
	$(call KCONFIG_SET_OPT,CONFIG_CRYPTO_DEV_SAFEXCEL,m)
endef

LINUX_DTS_MT7988 = $(LINUX_DIR)/arch/arm64/boot/dts/mediatek

define BANANAPI_BPI_R4_KERNEL_DTBS_INSTALL_TARGET
	@$(call MESSAGE,"Installing kernel DTBs and DTBOs for BPI-R4")
	$(foreach f, \
		mt7988a-bananapi-bpi-r4.dtb \
		mt7988a-bananapi-bpi-r4-2g5.dtb \
		mt7988a-bananapi-bpi-r4-sd.dtbo \
		mt7988a-bananapi-bpi-r4-emmc.dtbo, \
		$(INSTALL) -D $(LINUX_DTS_MT7988)/$(f) \
			$(TARGET_DIR)/boot/mediatek/$(f)$(sep))
endef
BANANAPI_BPI_R4_POST_INSTALL_TARGET_HOOKS += BANANAPI_BPI_R4_KERNEL_DTBS_INSTALL_TARGET

$(eval $(ix-board))
$(eval $(generic-package))
