# Use <pid/syslogd> as barrier for other system tasks and service that
# rely on modules, firmware, and device nodes to be ready.
service if:keventd nowarn env:-/etc/default/sysklogd <service/keventd/ready> \
	[S0123456789] syslogd -8 -F $SYSLOGD_ARGS -- System log daemon
