dtb-y += broadcom/bcm2837-rpi-3-b.dtb broadcom/bcm2837-rpi-zero-2-w.dtb \
	 broadcom/bcm2711-rpi-4-b.dtb broadcom/bcm2711-rpi-4-b-dsi.dtb  \
	 broadcom/bcm2711-rpi-400.dtb broadcom/bcm2711-rpi-cm4-io.dtb
