label Infix (aarch64)
	kernel /boot/Image
	fdtdir /boot
	fdtoverlays /boot/mediatek/mt7988a-bananapi-bpi-r4-sd.dtbo /boot/infix/bananapi,bpi-r4.dtbo
	append ${bootargs_root} ${bootargs_log} usbcore.authorized_default=2 -- ${bootargs_user}
