dtb-y += marvell/armada-3720-espressobin.dtb
dtb-y += marvell/armada-3720-espressobin-emmc.dtb
dtb-y += marvell/armada-3720-espressobin-ultra.dtb
dtb-y += marvell/armada-3720-espressobin-v7.dtb
dtb-y += marvell/armada-3720-espressobin-v7-emmc.dtb
