#!/bin/sh
# Check for available software updates and notify on login if one exists.
# Called by the scheduler.

NOTIFY_FILE=/run/os-update
TAG=os-update

. /usr/libexec/infix/update-common

update_probe
rc=$?
if [ $rc -eq 1 ]; then
    exit 1
fi
if [ $rc -eq 2 ]; then
    logger -p daemon.info -t "$TAG" "Update check skipped: could not reach ${API_URL}"
    exit 0
fi

if update_available; then
    RELEASE_URL="${UPDATE_URL}/releases/${LATEST_TAG}"
    MSG="Software update available: ${LATEST_TAG}, running ${VERSION} (see ${RELEASE_URL})"
    logger -t "$TAG" "$MSG"
    printf '%s\n' "$MSG" > "$NOTIFY_FILE"
else
    logger -p daemon.debug -t "$TAG" "No update available (current: $VERSION, latest: $LATEST)"
    printf '' > "$NOTIFY_FILE"
fi
