SYMREG_VERSION = cb96993eeb34558926a8f5851a945ad4cd674690
SYMREG_SITE = $(call github,microchip-ung,symreg-tool,$(SYMREG_VERSION))
SYMREG_LICENSE = MIT
SYMREG_LICENSE_FILES = LICENSE
SYMREG_CONF_OPTS = -DBUILD_LAN969X=ON

define SYMREG_LINUX_CONFIG_FIXUPS
	$(call KCONFIG_ENABLE_OPT,CONFIG_SPARX5_SYMREG)
endef

$(eval $(cmake-package))
