################################################################################
#
# Wi-Fi support
#
################################################################################

FEATURE_WIFI_PACKAGE_VERSION = 1.0
FEATURE_WIFI_PACKAGE_LICENSE = MIT

define FEATURE_WIFI_LINUX_CONFIG_FIXUPS
	$(call KCONFIG_ENABLE_OPT,CONFIG_WLAN)
	$(call KCONFIG_ENABLE_OPT,CONFIG_RFKILL)
	$(call KCONFIG_SET_OPT,CONFIG_MAC80211,m)
	$(call KCONFIG_SET_OPT,CONFIG_CFG80211,m)

	$(if $(filter y,$(BR2_PACKAGE_FEATURE_WIFI_MEDIATEK)),
		$(call KCONFIG_ENABLE_OPT,CONFIG_MT7601U)
		$(call KCONFIG_ENABLE_OPT,CONFIG_MT76x0U)
		$(call KCONFIG_ENABLE_OPT,CONFIG_MT76x0E)
		$(call KCONFIG_ENABLE_OPT,CONFIG_MT76x2E)
		$(call KCONFIG_ENABLE_OPT,CONFIG_MT76x2U)
		$(call KCONFIG_ENABLE_OPT,CONFIG_MT7603E)
		$(call KCONFIG_ENABLE_OPT,CONFIG_MT7615E)
		$(call KCONFIG_ENABLE_OPT,CONFIG_MT7663U)
		$(call KCONFIG_ENABLE_OPT,CONFIG_MT7915E)
		$(call KCONFIG_ENABLE_OPT,CONFIG_MT798X_WMAC)
		$(call KCONFIG_ENABLE_OPT,CONFIG_MT7921E)
		$(call KCONFIG_ENABLE_OPT,CONFIG_MT7921U)
		$(call KCONFIG_ENABLE_OPT,CONFIG_MT7996E)
		$(call KCONFIG_ENABLE_OPT,CONFIG_MT7925E)
		$(call KCONFIG_ENABLE_OPT,CONFIG_MT7925U)
	)
	$(if $(filter y,$(BR2_PACKAGE_FEATURE_WIFI_REALTEK)),
		$(call KCONFIG_ENABLE_OPT,CONFIG_WLAN_VENDOR_REALTEK)
		$(call KCONFIG_ENABLE_OPT,CONFIG_RTL8XXXU)
		$(call KCONFIG_ENABLE_OPT,CONFIG_RTL8XXXU_UNTESTED)
		$(call KCONFIG_ENABLE_OPT,CONFIG_RTW88)
		$(call KCONFIG_ENABLE_OPT,CONFIG_RTW88_8703B)
		$(call KCONFIG_ENABLE_OPT,CONFIG_RTW88_8723CS)
		$(call KCONFIG_ENABLE_OPT,CONFIG_RTW88_8723D)
		$(call KCONFIG_ENABLE_OPT,CONFIG_RTW88_8723DE)
		$(call KCONFIG_ENABLE_OPT,CONFIG_RTW88_8723DS)
		$(call KCONFIG_ENABLE_OPT,CONFIG_RTW88_8723DU)
		$(call KCONFIG_ENABLE_OPT,CONFIG_RTW88_8723X)
		$(call KCONFIG_ENABLE_OPT,CONFIG_RTW88_8821C)
		$(call KCONFIG_ENABLE_OPT,CONFIG_RTW88_8821CE)
		$(call KCONFIG_ENABLE_OPT,CONFIG_RTW88_8821CS)
		$(call KCONFIG_ENABLE_OPT,CONFIG_RTW88_8821CU)
		$(call KCONFIG_ENABLE_OPT,CONFIG_RTW88_8822B)
		$(call KCONFIG_ENABLE_OPT,CONFIG_RTW88_8822BE)
		$(call KCONFIG_ENABLE_OPT,CONFIG_RTW88_8822BS)
		$(call KCONFIG_ENABLE_OPT,CONFIG_RTW88_8822BU)
		$(call KCONFIG_ENABLE_OPT,CONFIG_RTW88_8822C)
		$(call KCONFIG_ENABLE_OPT,CONFIG_RTW88_8822CU)
		$(call KCONFIG_ENABLE_OPT,CONFIG_RTW88_8822CE)
		$(call KCONFIG_ENABLE_OPT,CONFIG_RTW89)
		$(call KCONFIG_ENABLE_OPT,CONFIG_RTW89_8851BE)
		$(call KCONFIG_ENABLE_OPT,CONFIG_RTW89_8852AE)
		$(call KCONFIG_ENABLE_OPT,CONFIG_RTW89_8852BE)
		$(call KCONFIG_ENABLE_OPT,CONFIG_RTW89_8852BTE)
		$(call KCONFIG_ENABLE_OPT,CONFIG_RTW89_8852CE)
		$(call KCONFIG_ENABLE_OPT,CONFIG_RTW89_8922AE)
		$(call KCONFIG_ENABLE_OPT,CONFIG_RTW89_DEBUGMSG)
	)
endef

$(eval $(generic-package))
