define BANANAPI_BPI_R64_LINUX_CONFIG_FIXUPS
	$(call KCONFIG_ENABLE_OPT,CONFIG_ARCH_MEDIATEK)
	$(call KCONFIG_ENABLE_OPT,CONFIG_MACH_MT7622)
	$(call KCONFIG_ENABLE_OPT,CONFIG_PINCTRL_MT7622)
	$(call KCONFIG_ENABLE_OPT,CONFIG_SERIAL_8250_MT6577)
	$(call KCONFIG_ENABLE_OPT,CONFIG_MTK_UART)
	$(call KCONFIG_ENABLE_OPT,CONFIG_MEDIATEK_WATCHDOG)
	# Ethernet subsystem clock controller — required for the eth MAC,
	# MT7531 DSA switch, and HSDMA to get their clocks from &ethsys.
	# Without this, eth probe fails and the switch is never detected.
	$(call KCONFIG_ENABLE_OPT,CONFIG_COMMON_CLK_MT7622_ETHSYS)
	# HIF subsystem clock controller — required for PCIe and USB.
	$(call KCONFIG_ENABLE_OPT,CONFIG_COMMON_CLK_MT7622_HIFSYS)
	$(call KCONFIG_ENABLE_OPT,CONFIG_MEDIATEK_GE_PHY)
	$(call KCONFIG_ENABLE_OPT,CONFIG_REALTEK_PHY)
	$(call KCONFIG_ENABLE_OPT,CONFIG_NET_VENDOR_MEDIATEK)
	$(call KCONFIG_ENABLE_OPT,CONFIG_NET_MEDIATEK_SOC)
	$(call KCONFIG_SET_OPT,CONFIG_NET_DSA_MT7530,m)
	$(call KCONFIG_SET_OPT,CONFIG_MT7603E,m)
	$(call KCONFIG_SET_OPT,CONFIG_PCIE_MEDIATEK,m)
	$(call KCONFIG_ENABLE_OPT,CONFIG_MMC_MTK)
	$(call KCONFIG_SET_OPT,CONFIG_USB_XHCI_MTK,m)
	$(call KCONFIG_SET_OPT,CONFIG_PHY_MTK_TPHY,m)
	$(call KCONFIG_SET_OPT,CONFIG_MTK_THERMAL,m)
	$(call KCONFIG_SET_OPT,CONFIG_MTK_SOC_THERMAL,m)
	$(call KCONFIG_SET_OPT,CONFIG_I2C_MT65XX,m)
	$(call KCONFIG_SET_OPT,CONFIG_PWM_MEDIATEK,m)
	$(call KCONFIG_SET_OPT,CONFIG_REGULATOR_MT6380,m)
	$(call KCONFIG_SET_OPT,CONFIG_NVMEM_MTK_EFUSE,m)
	$(call KCONFIG_SET_OPT,CONFIG_CRYPTO_DEV_SAFEXCEL,m)
	$(call KCONFIG_ENABLE_OPT,CONFIG_RTC_DRV_MT7622)
endef

$(eval $(ix-board))
$(eval $(generic-package))
