#!/bin/sh

yang_models="ietf-interfaces"

gen_test=ietf_interfaces/verify_all_interface_types/test.py
gen_iface=d3a

cli_commands="show-interfaces"

. $(readlink -f $(dirname $0)/../test.sh)
main "$@"
