################################################################################
#
# yangerd
#
################################################################################

YANGERD_VERSION = 1.0.0
YANGERD_SITE = $(BR2_EXTERNAL_INFIX_PATH)/src/yangerd
YANGERD_SITE_METHOD = local
YANGERD_GOMOD = github.com/kernelkit/infix/src/yangerd
YANGERD_LICENSE = BSD-2-Clause
YANGERD_LICENSE_FILES = LICENSE
YANGERD_REDISTRIBUTE = NO

YANGERD_BUILD_TARGETS = cmd/yangerd cmd/yangerctl
YANGERD_INSTALL_BINS = yangerd yangerctl

define YANGERD_INSTALL_EXTRA
	$(INSTALL) -D -m 0644 $(YANGERD_PKGDIR)/yangerd.conf \
		$(FINIT_D)/available/yangerd.conf
	ln -sf ../available/yangerd.conf $(FINIT_D)/enabled/yangerd.conf
	$(INSTALL) -d $(TARGET_DIR)/etc/default
	echo '# yangerd build-time feature flags (generated by yangerd.mk)' \
		> $(TARGET_DIR)/etc/default/yangerd
	echo 'YANGERD_ENABLE_WIFI=$(if $(BR2_PACKAGE_IW),true,false)' \
		>> $(TARGET_DIR)/etc/default/yangerd
	echo 'YANGERD_ENABLE_CONTAINERS=$(if $(BR2_PACKAGE_PODMAN),true,false)' \
		>> $(TARGET_DIR)/etc/default/yangerd
	echo 'YANGERD_ENABLE_GPS=$(if $(BR2_PACKAGE_GPSD),true,false)' \
		>> $(TARGET_DIR)/etc/default/yangerd
	echo 'YANGERD_LOG_LEVEL=deug' >> $(TARGET_DIR)/etc/default/yangerd
endef
YANGERD_POST_INSTALL_TARGET_HOOKS += YANGERD_INSTALL_EXTRA

$(eval $(golang-package))
