task name:ixinit [S] <pid/syslogd> \
	/usr/libexec/finit/runparts -bp /usr/libexec/infix/init.d \
	-- Probing system

task name:slot-check [2345] <service/rauc/ready> \
	/usr/libexec/infix/slot-check \
	-- Checking software partitions
