# Banana Pi BPI-M1 kernel configuration fixups
define BANANAPI_BPI_M1_LINUX_CONFIG_FIXUPS
	# Allwinner A20 SoC
	$(call KCONFIG_ENABLE_OPT,CONFIG_ARCH_SUNXI)
	$(call KCONFIG_ENABLE_OPT,CONFIG_MACH_SUN7I)
	$(call KCONFIG_ENABLE_OPT,CONFIG_SUNXI_SRAM)

	# Serial console
	$(call KCONFIG_ENABLE_OPT,CONFIG_SERIAL_8250)
	$(call KCONFIG_ENABLE_OPT,CONFIG_SERIAL_8250_CONSOLE)
	$(call KCONFIG_ENABLE_OPT,CONFIG_SERIAL_8250_DW)

	# Network: GMAC with Realtek PHY
	$(call KCONFIG_ENABLE_OPT,CONFIG_NET_VENDOR_STMICRO)
	$(call KCONFIG_ENABLE_OPT,CONFIG_STMMAC_ETH)
	$(call KCONFIG_ENABLE_OPT,CONFIG_STMMAC_PLATFORM)
	$(call KCONFIG_ENABLE_OPT,CONFIG_DWMAC_SUNXI)
	$(call KCONFIG_ENABLE_OPT,CONFIG_REALTEK_PHY)

	# MMC/SD and SATA
	$(call KCONFIG_ENABLE_OPT,CONFIG_MMC_SUNXI)
	$(call KCONFIG_ENABLE_OPT,CONFIG_AHCI_SUNXI)

	# AXP209 PMIC, supplies the CPU and USB VBUS regulators
	$(call KCONFIG_ENABLE_OPT,CONFIG_I2C)
	$(call KCONFIG_ENABLE_OPT,CONFIG_I2C_MV64XXX)
	$(call KCONFIG_ENABLE_OPT,CONFIG_MFD_AXP20X_I2C)
	$(call KCONFIG_ENABLE_OPT,CONFIG_REGULATOR_AXP20X)

	# USB Host, the PHY depends on POWER_SUPPLY, with keyboard and mouse
	$(call KCONFIG_ENABLE_OPT,CONFIG_POWER_SUPPLY)
	$(call KCONFIG_ENABLE_OPT,CONFIG_PHY_SUN4I_USB)
	$(call KCONFIG_SET_OPT,CONFIG_USB_EHCI_HCD,m)
	$(call KCONFIG_SET_OPT,CONFIG_USB_EHCI_HCD_PLATFORM,m)
	$(call KCONFIG_SET_OPT,CONFIG_USB_OHCI_HCD,m)
	$(call KCONFIG_SET_OPT,CONFIG_USB_OHCI_HCD_PLATFORM,m)
	$(call KCONFIG_ENABLE_OPT,CONFIG_USB_HID)
	$(call KCONFIG_SET_OPT,CONFIG_HID_GENERIC,m)

	# Power button on the AXP209, KEY_POWER for input-event-daemon
	$(call KCONFIG_ENABLE_OPT,CONFIG_INPUT_MISC)
	$(call KCONFIG_ENABLE_OPT,CONFIG_INPUT_AXP20X_PEK)

	# SPI header
	$(call KCONFIG_ENABLE_OPT,CONFIG_SPI_SUN4I)

	# Temperature: SoC sensor in the touchscreen controller, used by
	# the cpu-thermal zone to throttle, and AXP209 die temp over IIO
	$(call KCONFIG_ENABLE_OPT,CONFIG_TOUCHSCREEN_SUN4I)
	$(call KCONFIG_ENABLE_OPT,CONFIG_CPU_THERMAL)
	$(call KCONFIG_ENABLE_OPT,CONFIG_IIO)
	$(call KCONFIG_ENABLE_OPT,CONFIG_AXP20X_ADC)
	$(call KCONFIG_ENABLE_OPT,CONFIG_SENSORS_IIO_HWMON)

	# LEDs: green user LED on GPIO, RTL8211E PHY LEDs offloaded to
	# the PHY with the netdev trigger
	$(call KCONFIG_ENABLE_OPT,CONFIG_LEDS_GPIO)
	$(call KCONFIG_ENABLE_OPT,CONFIG_LEDS_TRIGGER_NETDEV)

	# HDMI output with framebuffer console, no HDMI audio in mainline
	$(call KCONFIG_ENABLE_OPT,CONFIG_DRM)
	$(call KCONFIG_SET_OPT,CONFIG_DRM_SUN4I,m)
	$(call KCONFIG_SET_OPT,CONFIG_DRM_SUN4I_HDMI,m)
	$(call KCONFIG_ENABLE_OPT,CONFIG_DRM_SUN4I_HDMI_CEC)
	$(call KCONFIG_SET_OPT,CONFIG_DRM_SUN4I_BACKEND,m)
	$(call KCONFIG_ENABLE_OPT,CONFIG_DRM_FBDEV_EMULATION)
	$(call KCONFIG_ENABLE_OPT,CONFIG_FB)
	$(call KCONFIG_ENABLE_OPT,CONFIG_FRAMEBUFFER_CONSOLE)

	# Watchdog, RTC and SID (unique chip ID)
	$(call KCONFIG_ENABLE_OPT,CONFIG_WATCHDOG)
	$(call KCONFIG_ENABLE_OPT,CONFIG_SUNXI_WATCHDOG)
	$(call KCONFIG_ENABLE_OPT,CONFIG_RTC_CLASS)
	$(call KCONFIG_ENABLE_OPT,CONFIG_RTC_DRV_SUNXI)
	$(call KCONFIG_ENABLE_OPT,CONFIG_NVMEM)
	$(call KCONFIG_ENABLE_OPT,CONFIG_NVMEM_SUNXI_SID)

	# Crypto hardware acceleration
	$(call KCONFIG_ENABLE_OPT,CONFIG_CRYPTO_DEV_ALLWINNER)
	$(call KCONFIG_ENABLE_OPT,CONFIG_CRYPTO_DEV_SUN4I_SS)
endef

$(eval $(ix-board))
$(eval $(generic-package))
