# -*- sh -*-
# Modules from sysrepo

MODULES=(
	"sysrepo@2024-10-25.yang"
	"sysrepo-factory-default@2024-05-02.yang"
	"sysrepo-monitoring@2023-08-11.yang"
	"sysrepo-notifications@2025-01-10.yang"
	"sysrepo-plugind@2022-08-26.yang"

	"ietf-datastores@2018-02-14.yang"
	"ietf-factory-default@2020-08-31.yang"
	"ietf-netconf@2013-09-29.yang"
	"ietf-netconf-acm@2018-02-14.yang"
	"ietf-netconf-notifications@2012-02-06.yang"
	"ietf-netconf-with-defaults@2011-06-01.yang"
	"ietf-origin@2018-02-14.yang"
	"ietf-yang-library@2016-06-21.yang"
	"ietf-yang-library@2019-01-04.yang"


	"iana-if-type@2014-05-08.yang"
	"ietf-interfaces@2018-02-20.yang"
	"ietf-ip@2018-02-22.yang"
	"ietf-network-instance@2019-01-21.yang"
	"ietf-restconf@2017-01-26.yang"
	"ietf-subscribed-notifications@2019-09-09.yang"
	"ietf-yang-patch@2017-02-22.yang"
	"ietf-yang-push@2019-09-09.yang"
)
