server {
    listen       80;
    listen       [::]:80;
    server_name  network.local;

    location / {
        include /etc/nginx/netbrowse.conf;
    }
}

server {
    listen       443 ssl;
    listen       [::]:443 ssl;
    server_name  network.local;
    include      ssl.conf;

    location / {
        include /etc/nginx/netbrowse.conf;
    }
}
